### ISSUE TITLE
vps hosting contradicts its self

### ISSUE THREAD

**Issue by ACPixel** [kevinp058/Indicima-Issues#10]
`We will fully manage your server and
help you with any issues you have.` 
on the home page. but on the vps page:
`We currently to not provide managed VPS solutions, however we are here to help you 24/7. We will support you along the way.`
while yes, they are in two different spectrums. it could get confusing.

**Comment by kevinp058** [comment]
Error from old project - to be fixed

**Comment by kevinp058** [comment]
Fixed
