### ISSUE TITLE
grammer and general "englishness"

### ISSUE THREAD

**Issue by ACPixel** [kevinp058/Indicima-Issues#6]
the about footer ```At Indicima, we are here to offer our clients with the best service possible. This is why our servers come on only the most premium hardware. Let us help your project grow.``` is a bit poorly worded imo. just preferance though.

**Comment by kevinp058** [comment]
Agreed, to be changed.

**Comment by kevinp058** [comment]
Changed this summary. Also added CSS fix for the "About Indicima" title being higher above other footer column titles.
