### ISSUE TITLE
on the about page

### ISSUE THREAD

**Issue by ACPixel** [kevinp058/Indicima-Issues#7]
under we are here to stay. the term `fiscally responsible` is a very obsolete term that is not used often. most people wont know what it means.  though you do say `debt-free` after, its still a little hard to understand.

**Comment by ACPixel** [comment]
yes i know this is mostly me just not being smart. but hey, its the internet, expect people to be dumb. make things stupid simple

**Comment by kevinp058** [comment]
About me is pending an update, current content is temporary, awaiting Ian to complete a new one

**Comment by kevinp058** [comment]
Updated that minor section. Will be a full revamp of the About page over the coming days.
