### ISSUE TITLE
grammer and spelling

### ISSUE THREAD

**Issue by ACPixel** [kevinp058/Indicima-Issues#8]
`Our founding members have spent many years in the hosting market and have gained extensive experience in this time. One day our founders realised there was two types of hosting` on the about page. should be 
`Our founding members have spent many years in the hosting market and have gained extensive experience in this time. One day our founders realized there were two types of hosting`

**Comment by kevinp058** [comment]
UK - US English

Will be changed to the US spelling.

**Comment by kevinp058** [comment]
Fixed.
